# プロンプト前の改行を無効化
add_newline = false

# ディレクトリを2行目に移動
# format = """
# $all\
# $fill\
# $cmd_duration\
# \n$character
# """
format = '$directory$git_branch$git_status$aws$gcloud$line_break$character'

command_timeout = 5000
scan_timeout = 2000

[line_break]
disabled = false

[character]
vimcmd_symbol = '[V](bold green)'

[directory]
truncation_length = 10
truncation_symbol = ' '
# git repositoryでもフルパスを表示
# truncate_to_repo = false
home_symbol = '~'
read_only = '󰌾 '
format = """
[$path]($style)\
[$read_only]($read_only_style)\
"""
style = 'bold fg:#80EBDF'
read_only_style = 'bold red'

[fill]
symbol = '─'
style = '#4d4d4d'

[docker_context]
disabled = true
#format = 'via [🐋 $context](blue bold)'

[container]
disabled = true
#format = '[$symbol \[$name\]]($style) '

[aws]
format = '[](fg:#583622)[$symbol($profile)(\($project\))(\($region\))]($style)[](fg:#583622)'
# style = '#ffa500'
style = 'fg:white bg:#583622'
symbol = ''
# force_display = true
# disabled = false
# [aws.region_aliases]
# ap-southeast-2 = 'au'
# us-east-1 = 'va'
# [aws.profile_aliases]
# CompanyGroupFrobozzOnCallAccess = 'Frobozz'

[gcloud]
# format = '[](fg:#28405c)[$symbol($profile)(\($project\))(\($region\))]($style)[](fg:#28405c)'
# style = 'fg:white bg:#28405c'
# symbol = ''
# [gcloud.project_aliases]
# very-long-project-name = 'vlpn'
disabled = true

[git_branch]
symbol = ""
# ignore_branches = ['master', 'main']
style = "fg:#cccc56 bg:#2b2b29"
format = """
[](fg:#2b2b29)\
[$symbol $branch]($style)\
"""

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
ahead = '⬆︎${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⬇︎${count}'
untracked = ''

style = "fg:#cccc56 bg:#2b2b29"
format = """
[$all_status$ahead_behind]($style)\
[](fg:#2b2b29)\
"""

[cmd_duration]
# min_time = 2
# show_milliseconds = true
format = ' took [$duration]($style)'

