model_reasoning_effort = "xhigh"
hide_agent_reasoning = true
network_access = true

notify = ["bash", "-lc", "afplay /System/Library/Sounds/Ping.aiff"]
model = "gpt-5.5"

[tools]
web_search = true

[tui]
theme = "monokai-extended-bright"
status_line = ["model-with-reasoning", "current-dir", "context-used", "model", "project-name", "git-branch", "context-remaining"]

[tui.model_availability_nux]
"gpt-5.5" = 4

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

# mcpは一旦コメントアウト
# [mcp_servers.context7]
# command = "npx"
# args = ["-y", "@upstash/context7-mcp@latest"]
#
# [mcp_servers.figma]
# command = "npx"
# args = ["-y", "mcp-remote", "http://127.0.0.1:3845/sse"]
#
# 下記サイトからコピー
# https://zenn.dev/dely_jp/articles/codex-cli-matome
