[tools]
aws-cli = "latest"
gcloud = "latest"

pnpm = "latest"

node = "latest"

bun = "latest"

chezmoi = "latest"

go = "latest"

java = "latest"

ecspresso = "latest"

kubectl = "latest"
kind = "latest"

helm = "latest"

kustomize = "latest"

hadolint = "latest"

eksctl = "latest"

# npm
"npm:@usebruno/cli" = "latest"
"npm:cdk-nag" = "latest"
gh = "latest"

[tasks.brew-bundle]
description = "brewのインストール一覧を`Brewfile_wsl`に書き出す(vscodeの設定は無視)"
run = "cd && brew bundle dump --force --no-vscode --file Brewfile_wsl"

[tasks.cdk-out-clear]
description = "cdk.outの不要ファイルを削除"
run = 'npx cdk-agc'
